/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendRouteImport } from './routes/trend'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as IndexRouteImport } from './routes/index'

const TrendRoute = TrendRouteImport.update({
  id: '/trend',
  path: '/trend',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/trend': typeof TrendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/trend': typeof TrendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/trend': typeof TrendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/favoritos' | '/trend'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favoritos' | '/trend'
  id: '__root__' | '/' | '/favoritos' | '/trend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritosRoute: typeof FavoritosRoute
  TrendRoute: typeof TrendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trend': {
      id: '/trend'
      path: '/trend'
      fullPath: '/trend'
      preLoaderRoute: typeof TrendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritosRoute: FavoritosRoute,
  TrendRoute: TrendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
